version: '3.8'

services:
  labui-next:
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - supabase_default

networks:
  supabase_default:
    external: true